<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0-android;net7.0-android;</TargetFrameworks>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Anjo.Android.Cashfree.Api</PackageId>
		<PackageVersion>2.1.18</PackageVersion>
		<AssemblyVersion>2.1.18</AssemblyVersion>
		<FileVersion>2.1.18</FileVersion>
		<Version>2.1.18</Version>
		<Title>Anjo Android Cashfree SDK</Title>
		<Authors>Wael Anjo</Authors>
		<Owners>Wael Anjo</Owners>
		<PackageProjectUrl>https://github.com/mhdwaelanjo/Anjo.Android.Cashfree</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<Description>.NET for Android (formerly Xamarin.Android) Binding Library - Cashfree Api</Description>
		<PackageReleaseNotes>Cashfree.Api SDK v2.1.18</PackageReleaseNotes>
		<Copyright>Copyright (c) 2024 Wael Anjo</Copyright>
		<PackageTags>Xamarin.Android, NET MAUI, MonoDroid, Cashfree, payment-gateway, payment-integration, global payments, Upi</PackageTags>
		<Summary>With Cashfree Payments, collect payments, make payouts, manage international payments and more.</Summary>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Jars\api-2.1.18.aar" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Xamarin.AndroidX.GridLayout" Version="1.0.0.22" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Anjo.Android.Cashfree.Analytics\Anjo.Android.Cashfree.Analytics.csproj" />
		<ProjectReference Include="..\Anjo.Android.Cashfree.Base\Anjo.Android.Cashfree.Base.csproj" />
		<ProjectReference Include="..\Anjo.Android.Cashfree.Core\Anjo.Android.Cashfree.Core.csproj" />
		<ProjectReference Include="..\Anjo.Android.Cashfree.ImageCaching\Anjo.Android.Cashfree.ImageCaching.csproj" />
		<ProjectReference Include="..\Anjo.Android.Cashfree.Network\Anjo.Android.Cashfree.Network.csproj" />
		<ProjectReference Include="..\Anjo.Android.Cashfree.Ui\Anjo.Android.Cashfree.Ui.csproj" />
	</ItemGroup>
</Project>