<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net7.0-android;net6.0-android;</TargetFrameworks>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Anjo.Android.Cashfree.Core</PackageId>
		<PackageVersion>2.0.7</PackageVersion>
		<AssemblyVersion>2.0.7</AssemblyVersion>
		<FileVersion>2.0.7</FileVersion>
		<Version>2.0.7</Version>
		<Title>Anjo Android Cashfree SDK</Title>
		<Authors>Wael Anjo</Authors>
		<Owners>Wael Anjo</Owners>
		<PackageProjectUrl>https://github.com/mhdwaelanjo/Anjo.Android.Cashfree</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<Description>.NET for Android (formerly Xamarin.Android) Binding Library - Cashfree Core</Description>
		<PackageReleaseNotes>Cashfree.Core SDK v2.0.7</PackageReleaseNotes>
		<Copyright>Copyright (c) 2023 Wael Anjo</Copyright>
		<PackageTags>Xamarin.Android, MonoDroid, Cashfree, Payment Gateway, global payments</PackageTags>
		<Summary>With Cashfree Payments, collect payments, make payouts, manage international payments and more.</Summary>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Jars\core-2.0.7.aar" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Xamarin.Google.Android.Play.Integrity" Version="1.0.2.1" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Anjo.Android.Cashfree.Analytics\Anjo.Android.Cashfree.Analytics.csproj" />
		<ProjectReference Include="..\Anjo.Android.Cashfree.Base\Anjo.Android.Cashfree.Base.csproj" />
		<ProjectReference Include="..\Anjo.Android.Cashfree.ImageCaching\Anjo.Android.Cashfree.ImageCaching.csproj" />
		<ProjectReference Include="..\Anjo.Android.Cashfree.Network\Anjo.Android.Cashfree.Network.csproj" />
	</ItemGroup>
</Project>